version: '3.8'

services:
  connexus-be:
    image: connexus-be
    build:
      context: .
      dockerfile: ./apps/connexus-be/Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - 3000:3000
    restart: unless-stopped

  sow-rfq:
    image: sow-rfq
    build:
      context: .
      dockerfile: ./apps/sow-rfq/Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3004
    ports:
      - 3004:3004
    restart: unless-stopped
